from io import BytesIO
from typing import Any

from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.shapes import Circle, Drawing, Line, Rect, String
from reportlab.lib import colors
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import KeepTogether, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

NAVY = HexColor("#071B32")
BLUE = HexColor("#159BD3")
CYAN = HexColor("#39C9F3")
GREEN = HexColor("#25A978")
RED = HexColor("#E65068")
AMBER = HexColor("#E8A936")
VIOLET = HexColor("#7257E8")
INK = HexColor("#17283F")
MUTED = HexColor("#637B90")
PALE = HexColor("#EEF7FC")
LINE_COLOR = HexColor("#D8E8F2")


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="ReportTitle", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=24, leading=28, textColor=colors.white, spaceAfter=4))
    styles.add(ParagraphStyle(name="ReportSubtitle", parent=styles["BodyText"], fontSize=9, leading=13, textColor=HexColor("#B7D6E9")))
    styles.add(ParagraphStyle(name="Section", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=14, leading=18, textColor=NAVY, spaceBefore=6, spaceAfter=8))
    styles.add(ParagraphStyle(name="SectionLabel", parent=styles["BodyText"], fontName="Helvetica-Bold", fontSize=7, leading=9, textColor=BLUE, spaceAfter=2))
    styles.add(ParagraphStyle(name="BodySmall", parent=styles["BodyText"], fontSize=8.5, leading=12, textColor=INK))
    styles.add(ParagraphStyle(name="Muted", parent=styles["BodyText"], fontSize=7.5, leading=10, textColor=MUTED))
    styles.add(ParagraphStyle(name="MetricValue", parent=styles["BodyText"], fontName="Helvetica-Bold", fontSize=19, leading=21, textColor=NAVY, alignment=TA_CENTER))
    styles.add(ParagraphStyle(name="MetricLabel", parent=styles["BodyText"], fontName="Helvetica-Bold", fontSize=6.5, leading=8, textColor=MUTED, alignment=TA_CENTER))
    return styles


def _header_footer(canvas, doc):
    canvas.saveState()
    width, height = A4
    canvas.setFillColor(NAVY)
    canvas.rect(0, height - 12 * mm, width, 12 * mm, stroke=0, fill=1)
    canvas.setFillColor(CYAN)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(18 * mm, height - 7.5 * mm, "SENTRAPIXEL SOC")
    canvas.setFillColor(HexColor("#B7D6E9"))
    canvas.setFont("Helvetica", 7)
    canvas.drawRightString(width - 18 * mm, height - 7.5 * mm, "EVIDENCE-BACKED INCIDENT INTELLIGENCE")
    canvas.setStrokeColor(LINE_COLOR)
    canvas.line(18 * mm, 12 * mm, width - 18 * mm, 12 * mm)
    canvas.setFillColor(MUTED)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(18 * mm, 7.5 * mm, "Generated by SentraPixel SOC - Human approval required")
    canvas.drawRightString(width - 18 * mm, 7.5 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _metric_card(value, label, styles, color):
    return Table([[Paragraph(str(value), styles["MetricValue"])], [Paragraph(label.upper(), styles["MetricLabel"])]], colWidths=[36 * mm], rowHeights=[13 * mm, 7 * mm], style=TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), HexColor("#F8FCFF")), ("BOX", (0, 0), (-1, -1), .7, color),
        ("LINEABOVE", (0, 0), (-1, 0), 3, color), ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 2), ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))


def _risk_donut(score, severity):
    drawing = Drawing(75 * mm, 49 * mm)
    pie = Pie()
    pie.x, pie.y, pie.width, pie.height = 8 * mm, 4 * mm, 40 * mm, 40 * mm
    pie.data = [max(.01, score), max(.01, 100 - score)]
    risk_color = RED if score >= 85 else AMBER if score >= 35 else GREEN
    pie.slices[0].fillColor, pie.slices[1].fillColor = risk_color, HexColor("#E5EEF4")
    pie.slices.strokeWidth = 0
    drawing.add(pie)
    drawing.add(Circle(28 * mm, 24 * mm, 13 * mm, fillColor=colors.white, strokeColor=colors.white))
    drawing.add(String(28 * mm, 25.5 * mm, str(score), fontName="Helvetica-Bold", fontSize=18, textAnchor="middle", fillColor=NAVY))
    drawing.add(String(28 * mm, 20 * mm, "RISK / 100", fontName="Helvetica-Bold", fontSize=6, textAnchor="middle", fillColor=MUTED))
    drawing.add(String(53 * mm, 30 * mm, severity.upper(), fontName="Helvetica-Bold", fontSize=10, fillColor=risk_color))
    drawing.add(String(53 * mm, 24 * mm, "Overall severity", fontName="Helvetica", fontSize=7, fillColor=MUTED))
    drawing.add(String(53 * mm, 16 * mm, "Evidence-based", fontName="Helvetica-Bold", fontSize=7, fillColor=BLUE))
    return drawing


def _factor_chart(incident):
    short_labels = {
        "Suspicious successful login": "Suspicious login",
        "Sensitive resource accessed": "Sensitive access",
        "Large outbound data transfer": "Outbound transfer",
        "Security control evasion": "Defense evasion",
    }
    items = [("Base severity", max((event.get("base_severity", 0) for event in incident.get("events", [])), default=0))]
    items.extend((short_labels.get(factor.get("label"), factor.get("label", "Factor")), factor.get("points", 0)) for factor in incident.get("factors", []))
    height = max(35 * mm, (len(items) * 9 + 10) * mm / 3)
    drawing = Drawing(92 * mm, height)
    max_value = max([value for _, value in items] + [1])
    palette = [BLUE, VIOLET, RED, AMBER, GREEN, CYAN]
    for index, (label, value) in enumerate(items):
        y = height - 9 * mm - index * 8 * mm
        drawing.add(String(0, y + 1.5 * mm, label[:32], fontName="Helvetica", fontSize=6.5, fillColor=INK))
        drawing.add(Rect(38 * mm, y, 43 * mm, 3.5 * mm, fillColor=HexColor("#E7EFF5"), strokeColor=None))
        drawing.add(Rect(38 * mm, y, max(1.5 * mm, 43 * mm * value / max_value), 3.5 * mm, fillColor=palette[index % len(palette)], strokeColor=None))
        drawing.add(String(84 * mm, y + .6 * mm, str(value), fontName="Helvetica-Bold", fontSize=6.5, fillColor=NAVY))
    return drawing


def _timeline_graph(events):
    width, height = 170 * mm, 34 * mm
    drawing = Drawing(width, height)
    if not events:
        drawing.add(String(0, 15 * mm, "No timeline events available", fontName="Helvetica", fontSize=8, fillColor=MUTED))
        return drawing
    left, right, axis_y = 8 * mm, width - 8 * mm, 18 * mm
    drawing.add(Line(left, axis_y, right, axis_y, strokeColor=HexColor("#A8D7E9"), strokeWidth=1.5))
    step = (right - left) / max(1, len(events) - 1)
    for index, event in enumerate(events):
        x = left + index * step
        severity = event.get("base_severity", 0)
        node_color = RED if severity >= 65 else AMBER if severity >= 35 else GREEN
        drawing.add(Circle(x, axis_y, 3.2 * mm, fillColor=node_color, strokeColor=colors.white, strokeWidth=1.5))
        drawing.add(String(x, axis_y + 6 * mm, event.get("time", "-"), fontName="Helvetica-Bold", fontSize=6.5, textAnchor="middle", fillColor=BLUE))
        drawing.add(String(x, axis_y - 7 * mm, event.get("stage", "Event")[:20], fontName="Helvetica-Bold", fontSize=5.8, textAnchor="middle", fillColor=INK))
        drawing.add(String(x, axis_y - 11 * mm, event.get("id", "")[:16], fontName="Helvetica", fontSize=5.3, textAnchor="middle", fillColor=MUTED))
    return drawing


def generate_incident_report(incident: dict[str, Any], investigation: dict[str, Any], decision: str = "Pending human review") -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=18 * mm, leftMargin=18 * mm, topMargin=18 * mm, bottomMargin=17 * mm, title=f"SentraPixel SOC - {incident['incident_id']}")
    styles = _styles()
    severity, score = incident.get("severity", "unknown"), int(incident.get("score", 0))
    confidence, metrics = int(incident.get("confidence", 0)), incident.get("metrics", {})
    response_plan, verification = investigation.get("response_plan") or {}, investigation.get("verification") or {}
    verdict = verification.get("verdict", "needs_review")

    hero = Table([[Paragraph("SENTRAPIXEL SOC", styles["SectionLabel"])], [Paragraph("Incident Intelligence Report", styles["ReportTitle"])], [Paragraph(f"{incident['incident_id']}  |  {incident.get('title', 'Security Incident')}", styles["ReportSubtitle"])]], colWidths=[174 * mm], style=TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY), ("LEFTPADDING", (0, 0), (-1, -1), 10 * mm), ("RIGHTPADDING", (0, 0), (-1, -1), 10 * mm),
        ("TOPPADDING", (0, 0), (-1, 0), 7 * mm), ("BOTTOMPADDING", (0, -1), (-1, -1), 7 * mm),
    ]))
    cards = Table([[
        _metric_card(f"{score}/100", "Risk score", styles, RED if score >= 85 else AMBER),
        _metric_card(f"{confidence}%", "Confidence", styles, BLUE),
        _metric_card(metrics.get("correlated_alerts", 0), "Correlated alerts", styles, VIOLET),
        _metric_card(metrics.get("noise_reduced", 0), "Noise reduced", styles, GREEN),
    ]], colWidths=[43.5 * mm] * 4, style=TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 2), ("RIGHTPADDING", (0, 0), (-1, -1), 2)]))

    story = [hero, Spacer(1, 6 * mm), cards, Spacer(1, 6 * mm), Paragraph("EXECUTIVE SUMMARY", styles["SectionLabel"]), Paragraph(incident.get("summary", "No summary available."), styles["BodySmall"]), Spacer(1, 2 * mm)]
    story.extend([
        Table([[Paragraph(f"<b>Status:</b> {incident.get('status', 'open').replace('_', ' ').title()}", styles["Muted"]), Paragraph(f"<b>Analyst decision:</b> {decision}", styles["Muted"]), Paragraph(f"<b>Verification:</b> {verdict.replace('_', ' ').title()}", styles["Muted"])]], colWidths=[58 * mm] * 3, style=TableStyle([("BACKGROUND", (0, 0), (-1, -1), PALE), ("BOX", (0, 0), (-1, -1), .5, LINE_COLOR), ("PADDING", (0, 0), (-1, -1), 6)])),
        Spacer(1, 5 * mm), Paragraph("RISK INTELLIGENCE", styles["SectionLabel"]),
        Table([[_risk_donut(score, severity), _factor_chart(incident)]], colWidths=[76 * mm, 98 * mm], style=TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE"), ("BOX", (0, 0), (-1, -1), .5, LINE_COLOR), ("BACKGROUND", (0, 0), (-1, -1), HexColor("#FBFDFF")), ("PADDING", (0, 0), (-1, -1), 5)])),
        Spacer(1, 5 * mm), Paragraph("ATTACK PROGRESSION", styles["SectionLabel"]), KeepTogether([_timeline_graph(incident.get("events", [])), Spacer(1, 2 * mm)]),
    ])

    timeline = [["Time", "Stage", "Source", "Evidence"]]
    for event in incident.get("events", []):
        timeline.append([event.get("time", "-"), event.get("stage", "-"), event.get("source", "-"), Paragraph(event.get("label") or event.get("type", "-"), styles["Muted"])])
    timeline_table = Table(timeline, colWidths=[20 * mm, 38 * mm, 30 * mm, 86 * mm], repeatRows=1)
    timeline_table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), NAVY), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"), ("FONTSIZE", (0, 0), (-1, -1), 7), ("GRID", (0, 0), (-1, -1), .4, LINE_COLOR), ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, HexColor("#F7FBFE")]), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("PADDING", (0, 0), (-1, -1), 5)]))
    story.extend([timeline_table, PageBreak(), Paragraph("MITRE ATT&CK COVERAGE", styles["Section"])])

    mitre_rows = [["Technique", "Tactic", "Mapped evidence"]]
    for item in incident.get("mitre_techniques", []):
        mitre_rows.append([f"{item.get('id', '-')}  {item.get('name', '-')}", item.get("tactic", "-"), Paragraph(item.get("evidence", "-"), styles["Muted"])])
    if len(mitre_rows) == 1:
        mitre_rows.append(["No mapping", "-", "No MITRE evidence available"])
    mitre_table = Table(mitre_rows, colWidths=[55 * mm, 38 * mm, 81 * mm], repeatRows=1)
    mitre_table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), BLUE), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"), ("FONTSIZE", (0, 0), (-1, -1), 7), ("GRID", (0, 0), (-1, -1), .4, LINE_COLOR), ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, PALE]), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("PADDING", (0, 0), (-1, -1), 6)]))
    story.extend([mitre_table, Spacer(1, 6 * mm), Paragraph("MULTI-AGENT ASSESSMENT", styles["Section"])])

    assessment = Table([[
        Paragraph("<b>INVESTIGATION AGENT</b><br/><br/>" + investigation.get("narrative", "No narrative available."), styles["BodySmall"]),
        Paragraph(f"<b>INDEPENDENT VERIFIER</b><br/><br/><font size='16'>{verification.get('checks_passed', 0)}/{verification.get('checks_total', 0)}</font><br/>{verdict.replace('_', ' ').upper()}", styles["BodySmall"]),
    ]], colWidths=[116 * mm, 58 * mm], style=TableStyle([("BACKGROUND", (0, 0), (0, 0), HexColor("#F3FAFE")), ("BACKGROUND", (1, 0), (1, 0), HexColor("#F0FBF6") if verdict == "verified" else HexColor("#FFF8E9")), ("BOX", (0, 0), (-1, -1), .6, LINE_COLOR), ("INNERGRID", (0, 0), (-1, -1), .6, LINE_COLOR), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("PADDING", (0, 0), (-1, -1), 9)]))
    story.extend([assessment, Spacer(1, 4 * mm)])

    checks = [["PASS", Paragraph(item, styles["BodySmall"])] for item in verification.get("supported_checks", [])]
    checks.extend(["WARN", Paragraph(item, styles["BodySmall"])] for item in verification.get("warnings", []))
    if checks:
        check_table = Table(checks, colWidths=[18 * mm, 156 * mm])
        check_table.setStyle(TableStyle([("TEXTCOLOR", (0, 0), (0, -1), GREEN), ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"), ("FONTSIZE", (0, 0), (-1, -1), 7), ("LINEBELOW", (0, 0), (-1, -2), .3, LINE_COLOR), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("PADDING", (0, 0), (-1, -1), 5)]))
        story.extend([check_table, Spacer(1, 6 * mm)])

    story.append(Paragraph("RESPONSE PLAN", styles["Section"]))
    plan_groups = [("IMMEDIATE CONTAINMENT", response_plan.get("immediate_actions") or incident.get("recommended_actions", []), RED), ("PRESERVE EVIDENCE", response_plan.get("evidence_to_preserve", []), BLUE), ("RECOVERY", response_plan.get("recovery_steps", []), GREEN)]
    plan_cells = []
    for title, items, color in plan_groups:
        text = f"<b>{title}</b><br/><br/>" + "<br/>".join(f"{index + 1}. {item}" for index, item in enumerate(items or ["No action supplied"]))
        plan_cells.append(Table([[Paragraph(text, styles["BodySmall"])]], colWidths=[54 * mm], style=TableStyle([("LINEABOVE", (0, 0), (-1, 0), 3, color), ("BACKGROUND", (0, 0), (-1, -1), HexColor("#F9FCFE")), ("BOX", (0, 0), (-1, -1), .5, LINE_COLOR), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("PADDING", (0, 0), (-1, -1), 8)])))
    story.extend([Table([plan_cells], colWidths=[58 * mm] * 3, style=TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 2), ("RIGHTPADDING", (0, 0), (-1, -1), 2)])), Spacer(1, 6 * mm)])
    story.append(Table([[Paragraph("HUMAN APPROVAL GATE", styles["SectionLabel"]), Paragraph("No containment action is executed automatically. The analyst must review evidence and approve or reject the simulated response plan.", styles["BodySmall"])]], colWidths=[45 * mm, 129 * mm], style=TableStyle([("BACKGROUND", (0, 0), (-1, -1), HexColor("#FFF8E9")), ("BOX", (0, 0), (-1, -1), .8, AMBER), ("VALIGN", (0, 0), (-1, -1), "MIDDLE"), ("PADDING", (0, 0), (-1, -1), 8)])))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buffer.getvalue()
