from io import BytesIO
from typing import Any

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle


def generate_incident_report(
    incident: dict[str, Any],
    investigation: dict[str, Any],
    decision: str = "Pending human review",
) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=f"SentraPixel SOC - {incident['incident_id']}",
    )
    styles = getSampleStyleSheet()
    story = [
        Paragraph("SentraPixel SOC Incident Report", styles["Title"]),
        Spacer(1, 8),
        Paragraph(f"<b>Incident ID:</b> {incident['incident_id']}", styles["BodyText"]),
        Paragraph(f"<b>Title:</b> {incident['title']}", styles["BodyText"]),
        Paragraph(f"<b>Severity:</b> {incident['severity'].upper()}", styles["BodyText"]),
        Paragraph(f"<b>Risk Score:</b> {incident['score']}/100", styles["BodyText"]),
        Paragraph(f"<b>Analyst Decision:</b> {decision}", styles["BodyText"]),
        Spacer(1, 12),
        Paragraph("Incident Summary", styles["Heading2"]),
        Paragraph(incident.get("summary", "No summary available."), styles["BodyText"]),
        Spacer(1, 10),
        Paragraph("Attack Timeline", styles["Heading2"]),
    ]

    timeline = [["Time", "Stage", "Event"]]
    for event in incident.get("events", []):
        timeline.append([
            event.get("time", "-"),
            event.get("stage", "-"),
            event.get("label") or event.get("type", "-"),
        ])
    table = Table(timeline, colWidths=[25 * mm, 45 * mm, 90 * mm], repeatRows=1)
    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, None),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("PADDING", (0, 0), (-1, -1), 5),
    ]))
    story.extend([table, Spacer(1, 12)])

    story.append(Paragraph("Correlation Evidence", styles["Heading2"]))
    for factor in incident.get("factors", []):
        story.append(Paragraph(f"• {factor}", styles["BodyText"]))

    story.extend([
        Spacer(1, 10),
        Paragraph("AI Investigation", styles["Heading2"]),
        Paragraph(
            f"<b>Provider:</b> {investigation.get('provider', 'fallback')}",
            styles["BodyText"],
        ),
        Paragraph(investigation.get("narrative", "No narrative available."), styles["BodyText"]),
        Spacer(1, 8),
        Paragraph("Evidence", styles["Heading3"]),
    ])
    for item in investigation.get("evidence", []):
        story.append(Paragraph(f"• {item}", styles["BodyText"]))

    story.extend([Spacer(1, 8), Paragraph("Recommended Next Steps", styles["Heading3"])])
    for item in investigation.get("next_steps", []):
        story.append(Paragraph(f"• {item}", styles["BodyText"]))

    story.extend([Spacer(1, 10), Paragraph("Response Actions", styles["Heading2"])])
    for action in incident.get("recommended_actions", []):
        story.append(Paragraph(f"• {action}", styles["BodyText"]))

    story.extend([
        Spacer(1, 16),
        Paragraph(
            "Human approval is required before any containment or response action is executed.",
            styles["Italic"],
        ),
        Paragraph("Generated by SentraPixel SOC", styles["BodyText"]),
    ])

    doc.build(story)
    return buffer.getvalue()
