import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, BarChart3, BrainCircuit, ChevronDown, ChevronRight, Cloud, Database, FileSearch, Fingerprint, Globe2, History, Laptop, Link2, ListChecks, LockKeyhole, Network, Radar, Search, Server, Settings, ShieldCheck, SlidersHorizontal, Upload, User, Waypoints, Zap } from "lucide-react";
import "./soc-shell.css";
import SocModule from "./SocModules";

const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
const groups=[
 {label:"COMMAND",items:[["command","SOC Overview",Radar],["live","Live Monitoring",Activity],["posture","Security Posture",ShieldCheck]]},
 {label:"DETECTION",items:[["alerts","Alert Center",AlertTriangle],["upload","Upload & Analyze",Upload],["detection","Threat Detection",Radar],["correlation","Correlation Engine",Link2],["anomaly","Anomaly Detection",Activity]]},
 {label:"INVESTIGATION",items:[["analysis","AI Investigation",BrainCircuit],["incidents","Incident Workbench",FileSearch],["evidence","Evidence Explorer",Fingerprint],["timeline","Attack Timeline",Waypoints],["mitre","MITRE ATT&CK",Network]]},
 {label:"INTELLIGENCE",items:[["intel","Threat Intelligence",Globe2],["ioc","IOC Lookup",Search],["ip","IP Reputation",Network],["domain","Domain / URL Analysis",Globe2],["hunt","Threat Hunting",Radar]]},
 {label:"RESPONSE",items:[["response","Response Center",LockKeyhole],["actions","Recommended Actions",ListChecks],["containment","Containment Queue",ShieldCheck],["approval","Approval Center",LockKeyhole],["false-positive","False Positive Review",ShieldCheck]]},
 {label:"ANALYTICS",items:[["risk","Risk Analytics",BarChart3],["trends","Incident Trends",BarChart3],["detection-analytics","Detection Analytics",Activity],["insights","AI Insights",BrainCircuit]]},
 {label:"REPORTING",items:[["reports","Incident Reports",FileSearch],["executive","Executive Reports",BarChart3],["report-history","Report History",History]]},
 {label:"SYSTEM",items:[["sources","Data Sources",Database],["integrations","Integrations",Link2],["rules","Detection Rules",SlidersHorizontal],["audit","Audit Logs",History],["settings","Settings",Settings]]}
];
const native={live:"Live Events",incidents:"Incidents",analysis:"Analysis",upload:"Command Center"};
const copy={posture:["Security Posture","Unified visibility into current exposure, analyst review readiness, and defensive coverage."],alerts:["Alert Center","Triage security alerts by severity, source, confidence, and investigation state."],detection:["Threat Detection","Review detections produced by identity, endpoint, network, and correlation signals."],anomaly:["Anomaly Detection","Surface behavior that deviates from expected identity, device, and network activity."],evidence:["Evidence Explorer","Inspect the entities and telemetry that support each incident conclusion."],timeline:["Attack Timeline","Reconstruct an incident as an ordered, evidence-linked attack sequence."],mitre:["MITRE ATT&CK","Map observed behavior to ATT&CK tactics and techniques."],intel:["Threat Intelligence","Enrich suspicious indicators with external and internal context."],ioc:["IOC Lookup","Investigate IP addresses, domains, URLs, hashes, users, and devices."],ip:["IP Reputation","Review reputation and contextual evidence for suspicious network addresses."],domain:["Domain / URL Analysis","Inspect domains and URLs for suspicious indicators."],hunt:["Threat Hunting","Search across telemetry for related identities, devices, indicators, and attack patterns."],response:["Response Center","Coordinate reversible containment and analyst-approved response actions."],actions:["Recommended Actions","Review evidence-grounded response recommendations before execution."],containment:["Containment Queue","Track temporary containment requests, expiry, rollback, and approval state."],approval:["Approval Center","Keep consequential response actions behind explicit human authorization."],"false-positive":["False Positive Review","Review dismissed detections and preserve analyst reasoning."],"detection-analytics":["Detection Analytics","Understand alert volume, correlation quality, severity distribution, and noise reduction."],insights:["AI Insights","Review AI-generated investigation narratives separately from deterministic evidence."],executive:["Executive Reports","Summarize incident volume, risk, response status, and SOC outcomes."],sources:["Data Sources","Manage SIEM, identity, endpoint, firewall, and uploaded JSON telemetry sources."],integrations:["Integrations","Connect intelligence, notification, storage, and security services."],rules:["Detection Rules","Review correlation and detection logic used by the deterministic analysis layer."],audit:["Audit Logs","Track investigations, analyst decisions, response actions, and report activity."],settings:["Settings","Configure workspace behavior, safety controls, integrations, and analyst preferences."]};

function triggerNative(label){[...document.querySelectorAll(".app-shell > aside nav button")].find(b=>b.textContent.includes(label))?.click()}

function Overview({select}){
 const [data,setData]=useState({incidents:[],summary:{}});
 const [twinFocus,setTwinFocus]=useState("core");
 const twinData={identity:["IDENTITY","Observed user activity and authentication context."],device:["ENDPOINT","Endpoint telemetry linked to the active investigation."],core:["SOC CORE","Correlation engine linking entities, time windows and attack sequence evidence."],cloud:["CLOUD","Cloud-side anomaly requiring supporting evidence."],external:["EXTERNAL","Suspicious external destination observed in the simulated topology."],server:["SERVER","Protected internal resource monitored by SentraPixel."]};
 useEffect(()=>{fetch(`${API}/api/incidents`).then(r=>r.ok?r.json():Promise.reject()).then(setData).catch(()=>{})},[]);
 const incidents=data.incidents||[],s=data.summary||{};
 const critical=incidents.filter(x=>x.severity==="critical").length,high=incidents.filter(x=>x.severity==="high").length,pending=incidents.filter(x=>x.status==="awaiting_review").length;
 const recent=incidents.slice(0,5);
 const bars=[42,58,38,71,55,82,64,91,73,66,88,61];
 return <div className="enterprise-overview">
  <div className="overview-top"><div><p>SECURITY OPERATIONS / COMMAND CENTER</p><h1>SOC Overview</h1><span>Unified detection, investigation and response visibility</span></div><div className="overview-actions"><button onClick={()=>select("hunt")}><Search/> Search telemetry</button><button className="hot" onClick={()=>select("upload")}><Upload/> Analyze alerts</button></div></div>
  <div className="overview-kpis">
   <article className="danger"><span><AlertTriangle/> CRITICAL INCIDENTS</span><strong>{critical}</strong><small>Requires immediate review</small></article>
   <article className="amber"><span><Zap/> HIGH RISK</span><strong>{high}</strong><small>Priority investigation queue</small></article>
   <article className="blue"><span><BrainCircuit/> INVESTIGATING</span><strong>{pending}</strong><small>Awaiting analyst decision</small></article>
   <article className="green"><span><ShieldCheck/> NOISE REDUCED</span><strong>{s.noise_reduction_percent||0}%</strong><small>Correlation efficiency</small></article>
   <article className="violet"><span><Database/> RECORDED CASES</span><strong>{s.total??incidents.length}</strong><small>Incident knowledge base</small></article>
  </div>
  <div className="overview-grid">
   <section className="overview-card digital-twin"><header><div><p>LIVE ENVIRONMENT</p><h2>SOC Digital Twin</h2></div><span className="live-dot">SIMULATION ACTIVE</span></header><div className="twin-grid"/><div className="twin-canvas"><i className="twin-link l1"/><i className="twin-link l2"/><i className="twin-link l3 threat"/><i className="twin-link l4 threat"/><i className="twin-link l5"/><button onClick={()=>setTwinFocus("identity")} className={"twin-node n-user "+(twinFocus==="identity"?"selected":"")}><User/><b>IDENTITY</b><small>analyst</small></button><button onClick={()=>setTwinFocus("device")} className={"twin-node n-device "+(twinFocus==="device"?"selected":"")}><Laptop/><b>ENDPOINT</b><small>LAP-042</small></button><button onClick={()=>setTwinFocus("core")} className={"twin-node n-core "+(twinFocus==="core"?"selected":"")}><Network/><b>SOC CORE</b><small>correlating</small></button><button onClick={()=>setTwinFocus("cloud")} className={"twin-node n-cloud threat "+(twinFocus==="cloud"?"selected":"")}><Cloud/><b>CLOUD</b><small>anomaly</small></button><button onClick={()=>setTwinFocus("external")} className={"twin-node n-external threat "+(twinFocus==="external"?"selected":"")}><Globe2/><b>EXTERNAL</b><small>suspicious</small></button><button onClick={()=>setTwinFocus("server")} className={"twin-node n-server "+(twinFocus==="server"?"selected":"")}><Server/><b>SERVER</b><small>protected</small></button></div><div className="twin-legend"><span><i/>Observed path</span><span><i className="bad"/>Suspicious path</span><span><i className="safe"/>Protected asset</span></div><div className="twin-inspector"><div><span>SELECTED ENTITY</span><strong>{twinData[twinFocus][0]}</strong><small>{twinData[twinFocus][1]}</small></div><button onClick={()=>select("evidence")}>Inspect evidence <ChevronRight/></button></div></section>
   <section className="overview-card threat-activity"><header><div><p>THREAT ACTIVITY</p><h2>Detection volume</h2></div><span className="live-dot">LIVE</span></header><div className="chart-wrap"><div className="chart-y"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="bar-chart">{bars.map((v,i)=><i key={i} style={{height:`${v}%`}}><b>{v}</b></i>)}</div></div><footer><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>NOW</span></footer></section>
   <section className="overview-card posture-card"><header><div><p>SECURITY POSTURE</p><h2>Operational readiness</h2></div><ShieldCheck/></header><div className="posture-ring"><div><strong>{Math.max(72,100-pending*5)}%</strong><span>POSTURE</span></div></div><div className="posture-rows"><p><span>Correlation engine</span><b>Healthy</b></p><p><span>Human approval gate</span><b>Enabled</b></p><p><span>AI investigation</span><b>Available</b></p></div></section>
   <section className="overview-card live-feed"><header><div><p>INCIDENT QUEUE</p><h2>Recent investigations</h2></div><button onClick={()=>select("incidents")}>View all <ChevronRight/></button></header>{recent.length?recent.map((x,i)=><button className="feed-row" key={x.incident_id} onClick={()=>select("incidents")}><span className={`feed-sev ${x.severity}`}/><div><strong>{x.title}</strong><small>{x.incident_id} · {x.metrics?.raw_alerts||0} alerts</small></div><em>{x.score}</em><span className={`severity-tag ${x.severity}`}>{x.severity}</span><ChevronRight/></button>):<div className="feed-empty"><Radar/><strong>No recorded incidents</strong><span>Analyze telemetry to populate the investigation queue.</span></div>}</section>
   <section className="overview-card mitre-overview"><header><div><p>MITRE ATT&CK</p><h2>Observed techniques</h2></div><button onClick={()=>select("mitre")}>Explore</button></header><div className="technique"><span>T1078</span><div><strong>Valid Accounts</strong><small>Initial Access · Persistence</small></div><b>HIGH</b></div><div className="technique"><span>T1041</span><div><strong>Exfiltration Over C2</strong><small>Exfiltration</small></div><b>HIGH</b></div><div className="technique"><span>T1490</span><div><strong>Inhibit System Recovery</strong><small>Impact</small></div><b>MED</b></div></section>
   <section className="overview-card copilot"><header><div><p>AI INVESTIGATION COPILOT</p><h2>Analyst assist</h2></div><span className="online"><i/> ONLINE</span></header><div className="copilot-hero"><BrainCircuit/><div><strong>Evidence-grounded workflow</strong><span>Correlate first. Use AI to explain the evidence. Keep response behind human approval.</span></div></div><div className="copilot-actions"><button onClick={()=>select("analysis")}><Search/> Investigate incident</button><button onClick={()=>select("hunt")}><Radar/> Hunt related activity</button><button onClick={()=>select("approval")}><LockKeyhole/> Review approvals</button></div></section>
  </div>
 </div>
}

export default function SocShell({children}){
 const[active,setActive]=useState("command"),[collapsed,setCollapsed]=useState(false),[open,setOpen]=useState(()=>Object.fromEntries(groups.map(g=>[g.label,true])));
 const module=useMemo(()=>copy[active],[active]);
 useEffect(()=>{
   const sync=(event)=>{
     const map={live:"live",incidents:"incidents",analysis:"analysis",batch:"analysis"};
     if(map[event.detail]) setActive(map[event.detail]);
     else if(event.detail==="command") setActive(current=>current==="command"?"command":"upload");
   };
   window.addEventListener("sentrapixel:view",sync);
   return()=>window.removeEventListener("sentrapixel:view",sync);
 },[]);
 function select(id){setActive(id);if(native[id])triggerNative(native[id]);window.scrollTo({top:0,behavior:"smooth"})}
 function openIncident(incidentId){setActive("analysis");window.dispatchEvent(new CustomEvent("sentrapixel:open-incident",{detail:incidentId}));window.scrollTo({top:0,behavior:"smooth"})}
 return <div className={`soc-shell ${collapsed?"soc-collapsed":""}`}><aside className="soc-sidebar"><div className="soc-brand"><div className="soc-logo"><ShieldCheck/></div>{!collapsed&&<div><strong>SentraPixel</strong><span>Autonomous SOC</span></div>}<button onClick={()=>setCollapsed(v=>!v)}><ChevronRight/></button></div><div className="soc-nav">{groups.map(g=><section key={g.label}>{!collapsed&&<button className="soc-group" onClick={()=>setOpen(v=>({...v,[g.label]:!v[g.label]}))}><span>{g.label}</span>{open[g.label]?<ChevronDown/>:<ChevronRight/>}</button>}{(collapsed||open[g.label])&&<div>{g.items.map(([id,label,Icon])=><button title={label} key={id} className={active===id?"active":""} onClick={()=>select(id)}><Icon/><span>{label}</span></button>)}</div>}</section>)}</div><div className="soc-engine"><span/><div><strong>ENGINE ONLINE</strong>{!collapsed&&<small>Evidence + human review</small>}</div></div></aside><div className="soc-content">{children}{active==="command"?<div className="soc-module-overlay overview-overlay"><Overview select={select}/></div>:native[active]?null:<SocModule id={active} navigate={select} openIncident={openIncident}/>}</div></div>
}